### ISSUE TITLE
virtual text of ray-x/lsp_signature.nvim gets removed

### ISSUE THREAD

**Issue by SamuelTJackson** [ms-jpq/coq_nvim#101]
When the suggestions pop up appears after writing e.g. `(` the virtual text of the signature help plugin disappears.

**Comment by ray-x** [comment]
FYI, the virtual text was created by:

`api.nvim_create_namespace("lsp_signature")`

**Comment by ms-jpq** [comment]
I think this might be solved now?

before I was using `nvim_buf_set_lines` which cleared out entire lines, and now i am using `nvim_buf_set_text`, which could preserve the virtual text.

---

not too sure though, because I couldnt get @ray-x 's excellent plugin to work on my config, I think there was some conflicts.

anyways, if @SamuelTJackson you could give me a quick test that could be great.

thanks!

**Comment by dnaaun** [comment]
I can confirm that ray-x/lsp_signature works well with the latest coq_nvim.

<img width="640" alt="Screen Shot" src="https://user-images.githubusercontent.com/52462475/131390133-7bd4a75c-3391-456f-a549-6dd505001f9d.png">

UPDATE: Welp! my last screenshot was with ray-x/lsp_signature using floating wins, here's one with virutal text 😂 

<img width="410" alt="Screen Shot with virtual text" src="https://user-images.githubusercontent.com/52462475/131390970-782395b5-4859-47de-b811-f1bf5962c673.png">

**Comment by ms-jpq** [comment]
thank u !
