### ISSUE TITLE
Add completion to the text history(?) so that it can be redone with '.' (period)

### ISSUE THREAD

**Issue by fakeharxy** [ms-jpq/coq_nvim#102]
When you've chosen an autocomplete from the dropdown, that selection should be saved as part of the text change.

If I change the word `created` to `delivered` and after 2 characters of delivered, I select it from the dropdown, and then go to the next instance of `created` and press `.` , I'll get `de` added to the text.

Cheers.

**Comment by ms-jpq** [comment]
humm interesting, I will see what I can do, I know [vim-repeat](https://github.com/tpope/vim-repeat) does something like this but for operations and such.

**Comment by ms-jpq** [comment]
this is harder than I thought, because things like LSP can send an edit request thats like `change text from line 13, pos 2 to line 14 pos 4` .

like what do i actually repeat in that case?

**Comment by ms-jpq** [comment]
im open to suggestions, but tabnine can also send multi-line edits, that edit text **before** where your cursor is.

honestly anything i implement **will not** be consistent with vim's `.` semantics, just because `coq` supports a much larger set of possible edit behaviour than vim.

and getting down what exactly will be the new behaviour should be, is the hard part

**Comment by ms-jpq** [comment]
@zeertzjq you always have good ideas, maybe you can help to chime in

**Comment by dannyfiresnake** [comment]
Making the behavior work for common cases that are simple is better than not making it work because of some other cases that are more complex. 

That said, you could always repeat the lsp modification command relative to where the cursor is. 

Also, while I'm here, I'd like to add that your attention to the performance of coq is much appreciated. 💯

**Comment by ms-jpq** [comment]
the thing right, is that the edit "from line `l1`, col `c1` to line `l2`, col `c2`" is actually not the exception, its the norm for several LSPs.

they will ask the LSP client to insert text that is basically like in the middle a symbol, like the complications im talking about aren't even exceptional, they are just how things work in general.

**Comment by ms-jpq** [comment]
im not supporting it right now, but there is also a type of LSP edit that is basically i think impossible to repeat with `.`,

it will ask to both do a delete and then an insert, all at the same time.

its pretty much impossible to figure out what to do in that case.

**Comment by ms-jpq** [comment]
maybe I can just save the word under cursor after the insertion and repeat that?

`l0l`

**Comment by zeertzjq** [comment]
One solution I can think of is to use `feedkeys` instead of `buf_set_text` for simple operations. This may complicate the code though.

**Comment by zeertzjq** [comment]
A possible quite hacky solution: if an instruction's replaced region ends at the cursor position:
1. Temporarily set `completeopt` to an empty string.
2. Call `complete()` with the start column of the replace region as the first argument and a tuple with the destination text as the only member as the second argument.
3. Use some method to stop completion so that the text won't disappear if the user presses Ctrl-P or Ctrl-N.
4. Restore the value of `completeopt`.

**Comment by dannyfiresnake** [comment]
coc.nvim does this just fine for the most common case that drives me nuts in coq.nvim:

let's say I have a `foo.bar`  and I move cursor over to `b` -- then I hit `cw` to change the `bar` into a different function name -- when I do that, the popup for completion appears and I pick something.

Then I want to go to the next calling of `.bar` or whatever, and hit `.`, and have it do `cw<textfromLSP><esc>`

It's killing me... you've put me in a very bad situation where I want coq's setup/performance so badly, but I fear I may have to go back to coc :-(

**Comment by ms-jpq** [comment]
well this is the next feature coming, but im gonna touch grass for a few days before then

**Comment by dannyfiresnake** [comment]
excellent! I'll hang on!

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/252

WIP

**Comment by ms-jpq** [comment]
nope, reverted the PR.

turns out there is almost no way to do this correctly without converting the edit from an api request "hey insert `<x>` here" to actually telling vim "hit back space a few times and paste `<x>`".

---

the issue is that there is almost no way to know exactly how many backspaces to hit. because well, **unicode**

Really almost no CLI text editors handle unicode correctly and I don't think its fesible to match what vim considers a single `grapheme cluster` bug for bug.

**Comment by ms-jpq** [comment]
The big issue is still that:

1) `coq` can delete backwards from where the edit is

2) the only way to manipulate the `.` (repeat) register is by simulating keystrokes.

**Comment by ms-jpq** [comment]
@dannydulai you should probably just give up and go back to `coc`. I don't think there can be a good solution to this anytime soon.

**Comment by ms-jpq** [comment]
I can't do it in the same way [`https://github.com/tpope/vim-repeat`](https://github.com/tpope/vim-repeat) can either. it just overwrites the `.` key, and unless i keep a history of every edit + keystroke, there will be lots of edge cases.

**Comment by ms-jpq** [comment]
I will just add a repeat button thats separate from `.`, because its too hard to make it behave the exact same way

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/259

**Comment by ms-jpq** [comment]
#### `coq_settings.keymap.repeat`

Repeat last edit performed by `coq`.

Note: this is not the same as `.` key in Vim. Vim's `.` key is pretty "dumb" as it simply stores and replays keystrokes, while `coq` performs arbitrary edits.

ie. typo correction, some LSP requests, multi-line Tabnine edits, etc

`coq` does not records it's edits in `.` history, because it's not feasible to translate any arbitrary edit into a sequence of `.` keystrokes without substantial edgecases.

ie. `coq` cannot realistically reproduce Vim's "unique" interpertion of unicode grapheme clusters bug for bug.

**default:**

```json
null
```

----

its in
