### ISSUE TITLE
Surprise window closure on startup with suckless dwm

### ISSUE THREAD

**Issue by krisezra87** [ms-jpq/coq_nvim#103]
I'm not exactly sure how to troubleshoot this, but when using dwm if I issue `:COQnow` or use the autostart variable, the whole parent window running neovim is closed.  I assume it is something to do with how you are closing processes for speedup, but this unfortunately exceeds my ability to diagnose.

Any thoughts?

**Comment by ms-jpq** [comment]
wild, maybe its cuz im issuing a [setsid](https://man7.org/linux/man-pages/man2/setsid.2.html) syscall. 

what i meant to do was to kill everything on exit including grandchildren processes, but maybe dwm doesnt like that? 

i will make a test variable for you and disable the grandchildren reaping behavior, and see if that helps.

this is just a hypothesis, since i dont actually use dwm, i will need your help to test :)

**Comment by krisezra87** [comment]
I am happy to be a tester (and I'm fairly competent I think).  As of today, 8/23, after updating coq the problem persists.  Is there some way I can help to troubleshoot or provide information?  I will start digging because I think you made a kick butt program (been using it on my wife's laptop) and I want to use it for "production"!

**Comment by krisezra87** [comment]
As a totally surprising turn of events, I can't even open \_\_main\_\_.py to read through it unless I use a virtual machine.  With vim or neovim or cat/less, as soon as I try to get into that file it closes the window.  I'm running python 3.9.6

**Comment by icyphox** [comment]
@krisezra87 Hah, something tells me this might be the issue:
https://github.com/ms-jpq/coq_nvim/blob/99f2799516f6eeaa52afe9163bb8c42506679dd9/coq/__main__.py#L22

Your terminal crashes because the fonts required to render that emoji are likely missing. Probably also why `:COQnow` kills your terminal — it spits out a bunch of emoji to the message buffer.

**Comment by ms-jpq** [comment]
I think you got it @icyphox. Thank you so much!

I didn't even consider any modern terminal would crash on valid unicode, but I guess `suckless` is special.

[Their own doc](https://git.suckless.org/st/file/FAQ.html) says there is a crash with certain emojis.

---

Well in that case, I guess ill close this issue, since I have no plans of to ensure ascii-only across both `coq.nvim` and the snippets i compile from across the internet. (That includes coq's documentation too, since I do have a help command that opens up the doc in a floating window).

It's not that this is not doable, but honestly it's 2021, and I don't think developers should still pretend its an english only world.

I am actually glad that emojis exist, just to drag all the big american developers to migrate towards better support for the vast diversity of human languages.

**Comment by krisezra87** [comment]
This is indeed a suckless-st problem, or more precisely it is an Xft problem that st leverages.  If anyone finds themselves in this situation there is an ugly workaround, but it's better than nothing!

[Found the fix here](https://git.suckless.org/libsl/commit/53ebcb48c6b12882c6dbe352ee43c96b2fb01b84.html#h0-0)

I added `FcPatternAddBool(fcpattern,FC_COLOR,0);` to x.c directly following the line `FcPatternAddBool(fcpattern,FC_SCALABLE,1)` and rebuilt.  Now the emojis don't render, but it doesn't crash either.

**Comment by ms-jpq** [comment]
lol you are so hard core :D,

personally I just use iTerm because im basic and it has good emoji support.

its so slow though, and kills my battery, 🤷‍♀️
