### ISSUE TITLE
Option to leave `showmode` unchanged

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#114]
This plugin sets `noshowmode`, but this plugin can work without changing this setting. Maybe there can be an option to leave `showmode` unchanged?

**Comment by mcchrish** [comment]
Indeed. `showmode` is quite important. I mean, it's the reliable way to tell what's the active mode.

**Comment by Shougo** [comment]
I think it is to reduce the flicker.

**Comment by ms-jpq** [comment]
@Shougo  is right, it was done to reduce the annoying flickering.

It's a trade off, from the FAQ:

---

#### Flickering

By default, the old results are cleared on each keystroke, so the popup menu is closed right away.

You can disable this: at the cost of having stale results shown until the new ones come in.

`let g:coq_settings = { 'display.pum.fast_close': v:false }`

This is not the default because some LSP servers are very slow (ie. tailwindcss), leading to stale results being shown for too long.

---

So now that when you can disable the `fast_close` option, the `showmode` option is not disabled by default.

**Comment by ms-jpq** [comment]
tailwindcss is particularly bad because by default, it even shows up in filetypes like `markdown`, leading to unreasonable lag in text files.

**Comment by mcchrish** [comment]
But why does `showmode` in particular affects the display of the completion items? I understand requiring `shortmess+=c` as it hides the completion messages in the commandline. But why the need to hide the whole mode completely?

**Comment by ms-jpq** [comment]
@mcchrish wait your are right, I disabled it by mistake. I thought showmode would flicker if I didn't turn it off, but turns out it wasnt needed.

I just removed it entirely.

**Comment by ms-jpq** [comment]
thank u!

<3

**Comment by mcchrish** [comment]
Awesome 🎉 
The two seems unrelated that i think they shouldn't affect each other. Otherwise I might report a bug on neovim.

Thanks for the quick response!
