### ISSUE TITLE
coq breaks ctrl-h | note: just change the default keymap

### ISSUE THREAD

**Issue by MinmoTech** [ms-jpq/coq_nvim#137]
While coq is activated and you try to use <C-h> as backspace (as is the default in vim) it immedeately exits insert mode with the message "⛔️ No more marks available"

**Comment by ms-jpq** [comment]
thats re-mappable:

```viml
let g:coq_settings = { 'keymap.jump_to_mark' : '<something else>' }
```

`<c-h>` just happens to be the key i picked for `<something else>`, because i found most people would just use backspace anyways.

if you need to use `<c-h>` for some reason, please pick another key :), or disable it by `let g:coq_settings = { 'keymap.jump_to_mark' : '' }`.

I will close this one because I think its reasonable to have default keybindings, and pretty much doesn't matter what key i pick, they are always gonna be conflicts.

**Comment by MinmoTech** [comment]
thanks!

**Comment by OmiChrome** [comment]
this is one issue is needed one , please pin this one !
