### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by matu3ba** [ms-jpq/coq_nvim#15]
Would be nice for potential code reuse or works based on coq_nvim etc to know the LICENSE.

**Comment by ms-jpq** [comment]
I just [wrote one](https://github.com/ms-jpq/coq_nvim/blob/coq/LICENSE) because I read that Richard Stallman did that once upon a time:

---

# LICENSE

I am going to write my own license, because I feel like it?

---

## Section 1. I will not sue you

I promise I will not sue you, you can believe me because honestly I am not rich enough to sue anybody.

I don't even know if writing my own license is legally a thing or not, but whatever, because I am not gonna sue you.

---

## Section 2. You can't sue me either

Ok so I guess this is just for my personal safety, but if my code ends up setting your fish tank on fire or something else thats also entirely horrible you can't sue me.

You are allowed to send me angry emails, but you consent to not suing me by using my code.

---

## Section 3. Notice me senpai

Eh, spirit of sharing and what not, if you can acknowledge that I, `ms-jpq` wrote this it would be very nice.

But I don't really like my Github name anyways, its one of those named I picked when I still thought MapleStory was a good game.

Its too late to change now though.

**Comment by icyphox** [comment]
Hi. Do you think you can license this under an OSI approved license? Writing your own license is probably not a good idea. A good choice would be MIT.

**Comment by CacheApp25** [comment]
I am SOOO sorry!! I did not intend for that file version to be deployed,
I'm new and learning and my file memory got cluster f****d since my last
backup / reconfiguration

**Comment by rudotriton** [comment]
or GPL, in the spirit of Stallman

**Comment by mortie** [comment]
So, I'm not a lawyer. And I'm not going to tell you why you shouldn't write your own license, because everyone will do that already anyways. But I'm going to critique your license. 

---

> Ok so I guess this is just for my personal safety, but if my code ends up setting your fish tank on fire or something else thats also entirely horrible you can't sue me.

This is worded weirdly and missing some punctuation, but the sentiment is okay enough I suppose. (Though according to this paragraph, I *can* sue you though if your code causes problems which aren't "entirely horrible"? Is that really your intention?)

> You are allowed to send me angry emails, but you consent to not suing me by using my code.

This is very dangerous though. I consent to not suing you by using your code? Like, in general? If you come to my house and break break my windows and kill my cat, I can't sue you because I used your code? That's probably not your intention, but it's what your license currently says.

I also believe this falls far outside of what you can do through copyright law. This falls inside the domain of contract law, meaning you have to make sure people accept your terms and conditions (namely that people who accept the license agree to not sue you, ever, for any reason). It's also probably not enforceable in most jurisdictions.

It turns out that a lot of the tricky wording in GPL-style licenses is exactly to get them to fall within copyright law and not contract law. That's why you don't have to click "I accept the terms and conditions" when using most FOSS projects, including projects using the GPL family of licenses.

> I promise I will not sue you, you can believe me because honestly I am not rich enough to sue anybody.

I don't know if this is enforceable. But if it is, you're giving up the right to sue anyone who uses your code. Anyone could do anything against you (at least anything which falls under the domain of civil law), and you can't sue them for it because you promised so in your license. If your employer causes you serious harm through negligence, you can't sue for compensation. You can't sue to get medical bills covered. If you ever make art and someone else takes it and sells it for profit, you can't sue them to get them to stop. If you ever get a child and there's a custody dispute, you can't bring that custody dispute to court to reach an agreement which allows you to see your child. All the entity you want to sue has to say is that they have used your code, so you can't sue them.

You probably meant you can't sue people _for what they do with your code_. But that's not what it says. Maybe a lawyer could argue in court that that's clearly what you meant, I don't know. I wouldn't bet my life on it.

None of this is probably going to happen, because the license will *probably* be ruled invalid somehow. But I don't know. I'm not a lawyer. I just know that what you wrote definitely isn't what you intended. And if it actually is ruled to be valid, it could cause some serious trouble for you.

---

So yeah, there's a reason most people don't write licenses. The GPL isn't just Stallman's little pet project; it has been reviewed by all of the FSF's top copyright lawyers, and revised until they're happy. You need a very good understanding of copyright law to know what you can put in a copyright license without ending up in contract law territory. And you need to seriously sit down and think through all the possible consequences of the text of the document. And you probably want other lawyers to review it - even if you were a lawyer yourself. Because this shit is dangerous.

**Comment by mortie** [comment]
If you want a license recommendation, I would recommend the MIT license: https://opensource.org/licenses/MIT

It's essentially exactly what you intended your license to do. You can do anything you want, as long as you preserve the license file, and there's no warranty of any kind ("you can't sue me if my software doesn't work" type stuff). It's short and sweet, understandable by normal humans. As a bonus, it's well understood by lawyers and has been tested in court so there's case law about how to interpret it.

**Comment by asdf8dfafjk** [comment]
Gpl can die in mordor fire. Mit/bad makes oss fun without woke virtue signalling

**Comment by ghost** [comment]
nice, I dig it

**Comment by ms-jpq** [comment]
@mortie oh wow jesus, ok ill put it down under something else

**Comment by ms-jpq** [comment]
OK its GPL v3 now.

@asdf8dfafjk , sorry it's not like I super like Stallman as a person or anything, I think he has some good ideas though.
