### ISSUE TITLE
Bug: bracket disappearing

### ISSUE THREAD

**Issue by quantum-booty** [ms-jpq/coq_nvim#150]
Language server: pyright

Press tab to select first option:
![image](https://user-images.githubusercontent.com/28958399/131232852-96c641db-32a5-4cf5-a5c1-893ec767158d.png)
Press ( to attempt writing print(), however the bracket disappears
![image](https://user-images.githubusercontent.com/28958399/131232838-ce00cc43-eb0c-400c-85d6-05b6c534c2f7.png)
and I have to press ( again:
![image](https://user-images.githubusercontent.com/28958399/131232842-034513b9-c13e-4f84-b437-71be2d5b5514.png)

**Comment by mcchrish** [comment]
Related: https://github.com/ms-jpq/coq_nvim/issues/121

**Comment by ms-jpq** [comment]
yeah unfortunately this is just an ugly side effect, I will need to think about how to fix this, but right now the behaviour is better than what we had before, which was just flat out putting the cursor in the wrong location.

I will think about how to do this.

**Comment by zeertzjq** [comment]
Theoretically anything can happen between CompleteDone and edit(), including any text change and cursor movement.

A solution I can think of:
1. If cursor moves to another line, don't remove anything and just apply the edits.
2. Split the line before and after by cursor position (`before` into `before_left` and `before_right`, `after` into `after_left` and `after_right`).
3. If `after_left` starts with `before_left` and `after_right` ends with `before_right`, this mean new text has been inserted around the original cursor, and the cursor has moved within the new text. Change the line to original, apply the edits, then apply the difference between `after_left` and `before_left` and the difference between `after_right` and `before_right`.
4. Otherwise, cursor has been moved outside the new text or new text has been inserted somewhere else in the line. Don't remove anything and just apply the edits.

Here "new text" means text inserted after `CompleteDone` is applies and before `edit()` is called.

**Comment by ms-jpq** [comment]
like fundamentally the issue is that `pynvim` deadlocks if you try to use `asyncio` in a blocking call.

the whole thing can be easily solved if `pynvim` didn't deadlock, we can just block the user input until resolve completes.

---

anything else is just a work around of that. if speed didn't matter so much, I'd just use a threadpool with futures to do everything. 

maybe its easier if I just moved away from `pynvim` and did my own rpc like how `coc` does, but that is potentially a ton of work, and im not sure if I should even try it.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/189

I think I got it

**Comment by ms-jpq** [comment]
its really kinda a smort / dumb solution, it basically does a `diff` on the line, calculates the exact byte by byte diffs between the two states, does a `patch`, and saves the diff.

the diff is then patched in after the changes have been applied.

**Comment by ms-jpq** [comment]
@zeertzjq thank you for putting alot of work into this one <3
