### ISSUE TITLE
Package manager to update tabnine. Clarifying tabnine CPU usage.

### ISSUE THREAD

**Issue by matu3ba** [ms-jpq/coq_nvim#16]
1. I dont see a way in the manual to [disable downloads](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/MISC.md).
I dont understand why it is needed at all, since packer.nvim etc can copy git projects easily.
Would changing the README to explain how to setup packer etc be okay for you?

2. The associated issues were closed via some commits (only starting lsp on request and not searching through ignored files).
Other issues were closed with like 20% CPU usage. Ideally some statistics what to expect on an example project would be nice.

**Comment by ms-jpq** [comment]
So sorry this is a documentation issue, 

Tabnine is not enabled by default, so you do not need to disable it if you are worried about their proprietary program, it comes disabled out of the box.

---

I have added this in the documentation now:

if you want to enable and try tabnine:

`coq_settings.clients.tabnine.enabled=true`

---

I actually didn't do a scientific benchmark the CPU usage of Tabnine, but I know from my statistical tracking that Tabnine indeed is slower than I am willing to put forth as a default option, considering that the slowest of all sources will be the bottleneck of everything else.

I get about 20-30% CPU usage on a fairly high end i7, which is also quite heavy, and I do not want people to have a bad impression of my project due to something that I cannot control.
