### ISSUE TITLE
Inserting snippet places cursor at end of snippet, rather than $1, $2 etc

### ISSUE THREAD

**Issue by beauwilliams** [ms-jpq/coq_nvim#197]
What one would expect is the cursor to be placed between the "" here after selecting this snippet.

![error](https://i.ibb.co/V2G9Ndq/ezgif-2-1304967ba33d.gif)

**Comment by ms-jpq** [comment]
the LSP didn't ask for the cursor to be placed where you wanted it to be:

![图片](https://user-images.githubusercontent.com/50598611/131769748-7269c69c-f231-4db2-b1d1-734ed9bd9678.png)

[the specs is here](https://github.com/microsoft/language-server-protocol/blob/main/snippetSyntax.md)

---


### Tabstops

With tabstops, you can make the editor cursor move inside a snippet. Use `$1`, `$2` to specify cursor locations. The number is the order in which tabstops will be visited, whereas `$0` denotes the final cursor position. Multiple tabstops are linked and updated in sync.

**Comment by ms-jpq** [comment]
i thought about just placing the cursor at the lowest `tabstop` before, but i think some snippets will suffer from it. so ill just stick to the specs. sorry

**Comment by ms-jpq** [comment]
In general, I designed `coq` to be error on the side of trusting LSPs to give good results, because for good LSPs, trying to second guess them is holding them back, an LSP will have much more semantic information than I could realistically work with.

I have been dialing back on that though, some LSPs are dumb AF and they bring everybody else down `._.`

**Comment by beauwilliams** [comment]
Okay fair enough makes sense to me :)

So in the meantime, I guess one would use `<c-h>` (or whichever they have mapped it to) to move around the snippet and edit the $1 ..$2 etc

i.e `coq_settings.keymap.jump_to_mark`

**Comment by ms-jpq** [comment]
yeah basically, it be like that sometimes.

**Comment by beauwilliams** [comment]
that's alright for now. snippet completion is always sore point. I had a function previously with compe to allow tab to move about snippet with vsnip ($1 $2) while still allowing it to navigate between completion menu. obviously overloading tab has its issues.

perhaps can figure out way to add function one can place in init.lua etc to make this happen, so you can just hit tab and it knows to go to $1 $2 etc. 

but at least its documented for now how to deal with this

**Comment by beauwilliams** [comment]
perhaps if we can find a way to detect if a mark is available, then one could use that to overload tab. 

like how I did previously, here's what I had going with vsnip using the jumpable flag

```
    elseif vim.fn.call("vsnip#available", {1}) == 1 then
        return t "<Plug>(vsnip-expand-or-jump)"
```

this way one could potentially hit `<cr>` to select the snippet, then press `<tab>` to move to the first mark of the snippet. not sure if its doable now. but I think this would be reasonable

**Comment by ms-jpq** [comment]
i have a custom snippet thing in the works, it will come in a bit, it will have like a repl for snippets, and what not.

just finished implementing pretty much the full LSP snippet spec today, with regex and basically shell substitutions, which was actually useless because out of the thousand of lsp snips i scrapped, only about a dozen actually used it, and even then, they were all of the most basic "(.*)" patterns except like 2 of them.

and none of them actually used the shell substitutions.

the next stop is basically to create the repl and see how long that takes

**Comment by beauwilliams** [comment]
> i have a custom snippet thing in the works, it will come in a bit, it will have like a repl for snippets, and what not.
> 
> just finished implementing pretty much the full LSP snippet spec today, with regex and basically shell substitutions, which was actually useless because out of the thousand of lsp snips i scrapped, only about a dozen actually used it, and even then, they were all of the most basic "(.*)" patterns except like 2 of them.
> 
> and none of them actually used the shell substitutions.
> 
> the next stop is basically to create the repl and see how long that takes

that's a great point. well if so few LSP snippets out there are using those features, it's likely nobody will miss them

if they REALLY wanted them, soon they could make a custom snippet to do so 👍
