### ISSUE TITLE
HTTP ERROR 403: FORBIDDEN

### ISSUE THREAD

**Issue by samrathchadha** [ms-jpq/coq_nvim#199]
This gets printed when I open vim. When my tabnine is disabled this doesn't show up and neither does my tabnine work

**Comment by ms-jpq** [comment]
humm, didn't 403 for me.

maybe they just temporarily blocked ur ip or something, then I can't really help cuz I don't own the servers. 🤷‍♀️ 

![图片](https://user-images.githubusercontent.com/50598611/131774994-9b303be7-bf9a-4c4b-bd77-b0790d809470.png)

**Comment by samrathchadha** [comment]
Is there anyway I can manually download it?

**Comment by ms-jpq** [comment]
humm, please try and see if you can do `curl -L 'https://update.tabnine.com/version'`

it that thing returns a 403 i suspect you are SOL. if not there is an inconvenient way to do it.

**Comment by ms-jpq** [comment]
anyways you are not losing much even if tabnine blocks u from their stuff. honestly the free version is not very good lol.

im tempted to buy the paid version to try it out but my credit card company thinks its too sus and won't let me pay unless i call them

**Comment by samrathchadha** [comment]
So i tried it, and i got an ip address(i think)

**Comment by samrathchadha** [comment]
And the free version tbh is decent, not great but decent

**Comment by PlatyPew** [comment]
I seem to also have this issue, are you perhaps running on an Apple Silicon Mac?
I tried doing `wget https://update.tabnine.com/3.2.28/arm64-apple-darwin/TabNine` and it shows 403 Forbidden

**Comment by samrathchadha** [comment]
I am, I'll raise an issue in tabnine's repo.
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/69572668/138436621-161e42c6-c661-463c-8d43-5a38404b7678.png">

**Comment by ms-jpq** [comment]
wait, i might have gotten url wrong and never noticed cuz i dont have M1.

ok will test

**Comment by PlatyPew** [comment]
Alternatively, you can download the zipped file from TabNine bundles and just manually copy the files

For M1, although `uname -m` returns `arm64`, but TabNine wants `aarch64` for some reason (not the best explanation, but basically instead of `arm64-apple-darwin`, TabNine expects `aarch64-apple-darwin`)

This is what I used to circumvent it as I couldn't find the link that downloads just the TabNine binary for arm64

```bash
COQ_PATH="$HOME/.config/nvim/plugged/coq_nvim/.vars"
TABNINE_VERSION=$(curl -fsSL https://update.tabnine.com/bundles/version)

mkdir -p $COQ_PATH/$TABNINE_VERSION/t9
mkdir -p $COQ_PATH/clients/t9

TARGET=$(uname -m)
if [[ ${TARGET} == "arm64" ]]; then
    TARGET="aarch64"
fi

curl -sS https://update.tabnine.com/bundles/$TABNINE_VERSION/$TARGET-apple-darwin/TabNine.zip > TabNine.zip
unzip -d $COQ_PATH/$TABNINE_VERSION/t9 TabNine.zip
chmod +x $COQ_PATH/$TABNINE_VERSION/t9/*
cp $COQ_PATH/$TABNINE_VERSION/t9/TabNine $COQ_PATH/clients/t9/

rm TabNine.zip
```

**Comment by ms-jpq** [comment]
thanks @PlatyPew good find!

---

hummmmmmmm so this is what happened:

I think they added `aarch64-apple-darwin` but only to the newer `bundles` uri, and not the older uri which was used in all of their install scripts previously.

they kept all the old URIs functional because they didn't want to break backwards compatibility, but never made an attempt on forward compatibility.

I don't have a M1 mac so I just assumed everything worked.

**Comment by ms-jpq** [comment]
its just freaking weird their server would return a `403` instead of `404` if you didn't get the uri.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/369

**Comment by Bug-Whisperer** [comment]
what's the fix for this issue again?
