### ISSUE TITLE
Completion deletes the right side texts

### ISSUE THREAD

**Issue by mcchrish** [ms-jpq/coq_nvim#207]
https://user-images.githubusercontent.com/7200153/131959903-e78d55c5-272e-4518-b6ac-e4f795d6a930.mov

https://user-images.githubusercontent.com/7200153/131960483-29548485-5c8e-482b-a7e4-ff71ee0ac705.mov

**Comment by mcchrish** [comment]
To be fair, it might be the intended behavior since it's trying to replace the cword under the cursor. In the case of say `'world again'`, it will only replace it to `'hello again'`.

**Comment by ms-jpq** [comment]
yeah this is expected, the basic resolution order for `<new-text>` that do not have location information:

1. try to see if the text can be inserted without touching anything:

ie. inserting `bcde` into `ab|ef` where `|` denotes the cursor position will result in `abcdef|`

this is the ideal case

otherwise

2. replace`<left-symbol><cword>` if `<new-text>` starts with a symbol, otherwise do `<cword>`

---

if the `<new-text>` comes with location information, either from a snippet, LSP, or Tabnine, the insertion is dictated by that instead.

**Comment by ms-jpq** [comment]
I think like this is reasonable, but if you disagree, please re-open this and i can maybe add in a toggle to disable this

**Comment by ms-jpq** [comment]
but it will be a lower priority issue:

my priorities are 

1. correctness

2. speed

3. features

4. feature toggles
