### ISSUE TITLE
Add sniphpets to snippets json

### ISSUE THREAD

**Issue by Mte90** [ms-jpq/coq_nvim#210]
I don't know if there is a template or something similar but as PHP developer I am using the snippets from https://github.com/sniphpets

It possible to add them too?

**Comment by dnaaun** [comment]
@ms-jpq  is working on user-defined snippets, (which should be done [in a couple of days](https://github.com/ms-jpq/coq_nvim/issues/211#issuecomment-912383984) ), so when that is finished, you will be able to simply install the specific snippet repos (using packer.nvim or vim-plug or whatever else you use to install neovim plugins) and coq should automatically pick up on them.*

\*I'm not totally certain of the final implementation. Ie, we might have to run some command like `:COQsnips` or something, but user-defined snippets are definitely coming.

**Comment by Mte90** [comment]
I was thinking too, my thoughts was mainly about the snippets repo that scrape various repository and maybe add this one too was simplier.

**Comment by ms-jpq** [comment]
ok yeah sorry Ill have to close this one, just added [custom snippets](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SNIPS.md).

those repos do not seem super popular, so I'd just keep them out of default.

---

there is also the issue of incompatibility, `coq.nvim` straight up **refuses** to import any snippets that executes **arbitrary code**.

and alot of those snippets in the linked repos do that.

this is a safety issue, because well, there is no way I can manually review thousands of snippets, and I do not want to ship something that can seriously mess up my user's computers.

it doesn't even have to be malicious, i've accidentally wrote commands that nuked my data multiple times. (not in `coq`, because I never let any arbitrary code execute, but in other areas)
