### ISSUE TITLE
Language!

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [ms-jpq/coq_nvim#245]
**PS**: Cool stuff though.

**Comment by ms-jpq** [comment]
🙏

**Comment by pianocomposer321** [comment]
@ms-jpq I 100% agree with @make-github-pseudonymous-again. This plugin looks super cool, but I’m resisting trying it or even reading the docs because every other word is profanity. Is it really necessary to swear so many times in the readme of a neovim completion plugin of all things? I really don’t see the point. The only thing I can think is that it’s supposed to be some sort of a joke, but if you ask me it’s not that funny. Nobody is laughing, and my guess is that I’m not the only one who’s been repelled by it…

**Comment by ms-jpq** [comment]
🤷‍♀️

**Comment by ms-jpq** [comment]
![图片](https://user-images.githubusercontent.com/50598611/132545827-6d0f1416-cd28-4158-a482-c420f1833abf.png)

![图片](https://user-images.githubusercontent.com/50598611/132545865-7dc281ea-3472-4fe7-9b68-10960c94fe5c.png)

---

oops i used one too many fuck, i guess I can't release this to teenagers

**Comment by pianocomposer321** [comment]
Actually, I count two too many…

**Comment by joselevelsup** [comment]
Yo I'm crying :rofl:

**Comment by ms-jpq** [comment]
Plan of correction: 

Assemble a focus group to investigate which `fuck` to remove in accordance with MPAA guidelines.

**Comment by UltiRequiem** [comment]
lmao :rofl:, but imo it is true that so many `fucks` are unnecessary

**Comment by JoseConseco** [comment]
I would suggest correction:   `fast as duck`   -  this should be easier for  sensitive people  (including me L) )

**Comment by LamprosPitsillos** [comment]
Like literally i came across this plugin , read the README.md , had a chuckle and the continued reading. Really who gets bothered by this stuff in this day and age?

**Comment by ms-jpq** [comment]
> Like literally i came across this plugin , read the README.md , had a chuckle and the continued reading. Really who gets bothered by this stuff in this day and age?

English teachers, when they teach kids about _authorial intent_, they tell the kids to read between the lines.

I hated that shit, couldn't give two fucks about it. 

Here, I spell it loud and clear, there are exactly two fucks in my markdowns, it literally tells you I give two fucks about this project.

**Comment by pianocomposer321** [comment]
🙄
If y’all can’t understand two (at least) people’s legitimate concern and constructive criticism without pretending the whole thing is just a joke, that’s fine with me. Forgive me for overstepping my bounds and pointing out that flippant use of profanity is neither useful nor flattering to the intelligence of those who do so. You’re only hurting yourselves.

**Comment by pianocomposer321** [comment]
> Like literally i came across this plugin , read the README.md , had a chuckle and the continued reading. Really who gets bothered by this stuff in this day and age?

Idk, I guess those people who have retained the ability to express themselves without having to swear every other word, for a start. Of course, you’re right, the number of those people is fast diminishing, as is clearly evident by the very existence of this plugin, among other things.

**Comment by LamprosPitsillos** [comment]
Oh well , OK we get it , its not necessary for him to use it but he want's to, and it isn't anything offensive to anyone really . No need to bring your dictionaries out and have an argument. I think this issue doesn't provide anything to the project and should be closed.

**Comment by ms-jpq** [comment]
> swear every other word

![图片](https://user-images.githubusercontent.com/50598611/132569045-4afda04d-92e6-4bb3-b4e6-db835c045a49.png)

---

Excuse me, it's `0.0149%` fuck.

**Comment by joselevelsup** [comment]
This is probably the best issue I read all day :rofl: :rofl:

**Comment by joselevelsup** [comment]
I don't think the language should be taken seriously, obviously its the software that makes the impact. Not the use of profanity. So as long as @ms-jpq doesn't give a fuck, neither should we.

**Comment by ms-jpq** [comment]
okok guys please don't attack @pianocomposer321.

I am sure they mean well, I was just having fun here, no ill will at all.

**Comment by ms-jpq** [comment]
Like really, if this was under `coq.nvim/coq_nvim` i'd think it would be a fair move to sanitize the repo of any expletives.

But you know its still under @ms-jpq, so I figured it's still up to me if I should keep it or not.

---

**Comment by pianocomposer321** [comment]
> Oh well , OK we get it , its not necessary for him to use it but he want's to, and it isn't anything offensive to anyone really . No need to bring your dictionaries out and have an argument. I think this issue doesn't provide anything to the project and should be closed.

Yeah, well it’s clearly offensive to someone, otherwise this issue wouldn’t be here. I actually thought about opening one like this, but decided against it because I thought maybe I was the only one who cared. But since this issue already existed, I decided I could put in my two cents.

Also, the issue *was* closed, but @ms-jpq chose to re-open it and pin it, presumably so everyone could join in on the fun of harassing one of the apparently only two people left on the internet who find filthy language offensive.

**Comment by pianocomposer321** [comment]
> Like really, if this was under `coq.nvim/coq_nvim` i'd think it would be a fair move to sanitize the repo of any expletives.
> 
> But you know its still under @ms-jpq, so I figured it's still up to me if I should keep it or not.

Of course it’s up to you. I wouldn’t mind so much if you just said “no” and closed it, or even just ignored it. But you started the argument. I didn’t intend to leave it at that. I seriously doubt that you’re going to change your mind. That’s fine. But I wanted to make my point. Now that I’ve done so, I don’t really care what you do.

**Comment by ms-jpq** [comment]
> Also, the issue was closed, but the author chose to re-open it and pin it, presumably so everyone could join in on the fun of harassing one of the apparently only two people left on the internet who find filthy language offensive.

---

Well this sucks, I didn't intent for anybody to harass you, and it was wrong of me to do that. I pinned it in the same vein when somebody had opened a [pull request fixing a single character typo](https://github.com/ms-jpq/coq_nvim/pull/12) `its` -> `it's`, I intentionally left it open because I was genuinely amused by it and thought it was hilarious.

To be totally honest, I also did find your comments super funny in the same way, and pinned it.

I should not have presumed that you were ok with jest, and it didn't occur to me that somebody would actually take issue with expletives as a sincere concern. So I made jokes about it, without realizing that you were actually quite offended by those.

**Comment by pianocomposer321** [comment]
> > Also, the issue was closed, but the author chose to re-open it and pin it, presumably so everyone could join in on the fun of harassing one of the apparently only two people left on the internet who find filthy language offensive.
> 
> Well this sucks, I didn't intent for anybody to harass you, and it was wrong of me to do that. I pinned it in the same vein when somebody had opened a [pull request fixing a single character typo](https://github.com/ms-jpq/coq_nvim/pull/12) `its` -> `it's`, I intentionally left it open because I was genuinely amused by it and thought it was hilarious.
> 
> To be totally honest, I also did find your comments super funny in the same way, and pinned it.
> 
> I should not have presumed that you were ok with jest, and it didn't occur to me that somebody would actually take issue with expletives as a sincere concern. So I made jokes about it, without realizing that you were actually quite offended by those.

Thank you for clarifying. To be perfectly honest, I didn’t really feel attacked at any point. I couldn’t care less what people on the internet think of me. I also realize that most people would just look at the readme and “chuckle and move on” as someone earlier put it. Since I’m in the minority (by quite a wide margin apparently), I can’t really expect you to change the whole readme for the sole purpose of pleasing me. As I said before, I don’t really care. I just wanted to put my opinion out there in case anyone wanted to hear it. I can see why my personal standards for what is acceptable might be laughable to some people, and I think now I better understand your motives for re-opening the discussion and pinning it.

No hard feelings.
