### ISSUE TITLE
Ghost text uses byte column instead of screen column

### ISSUE THREAD

**Issue by zeertzjq** [ms-jpq/coq_nvim#285]
`virt_text_win_col` is the screen column of the virtual text, but byte column is passed to it when showing ghost text. As a result, ghost text is not shown if current lines wraps, and is in the wrong position if current line contains tabs.

Simply passing `screencol()` will place ghost text in the wrong screen line if the current line wraps.

**Comment by zeertzjq** [comment]
BTW, why not just set extmark at `(row, col)` instead of `(row, 0)` and remove `virt_text_win_col`? Does it break something?

**Comment by hrsh7th** [comment]
FYI: I'm using `virtcol('.')` value for `virt_text_win_col`.

**Comment by zeertzjq** [comment]
> FYI: I'm using `virtcol('.')` value for `virt_text_win_col`.

It seems `virtcol('.')` doesn't work in a wrapped line.

**Comment by hrsh7th** [comment]
Oh... Yes. I've confirmed. I'm also consider it. If I get it work, I will post the solution here.

**Comment by ms-jpq** [comment]
@zeertzjq haha you are the champ, you always find stuff.

I only used `virt_text_win_col` because I saw it and was like "MORE PARAMETERS -> BETTER". turns out thats not correct.

---

@hrsh7th didn't expect to see you here, but since you are here I just want to let you know that I am starting work on a two way bridge between `nvim-cmp` and `coq-nvim`'s lua sources.

There are overlaps for sure, but I think overall both our plugins will benefit.

**Comment by hrsh7th** [comment]
I'm watching almost the repos that relates to LSP or completion :)

Sounds good. Thank you for inform me.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/commit/35ff574b5169332250e8f0a7364a0defbd01990a

seems fixed

**Comment by hrsh7th** [comment]
I gave up using `virt_text_win_col` too. Your fix seems perfect.
