### ISSUE TITLE
Some wired high usage of CPU with u-ctags

### ISSUE THREAD

**Issue by mkubasz** [ms-jpq/coq_nvim#288]
Hi, I just found that after saving files, e. g. .gitignore there is a high peak of around 200% CPU for about 15-20 seconds.
The second issue is that my CPU with ctags can use all my cores. Maybe that could be options to set some limitations around it?

**Comment by mkubasz** [comment]
Their issue with high CPU after save files is the same in LSP.

**Comment by ms-jpq** [comment]
thats weird, doe this happen without `coq.nvim`, or if you disable `ctags` client? `coq.nvim` does't have anything for saving files.

For `ctags` it's more of a polling thing where if it detects a files modification time is updated, it will run ctags on that particular file, which for `.gitignore` should not take 15 seconds?

**Comment by mkubasz** [comment]
![Screenshot-Sep17::21-49-00](https://user-images.githubusercontent.com/1952619/133845482-13ad53e2-eb8f-4be7-b00b-af886b2c62db.png)
With disabling ctags those processes running. 
And nothing happened when I disable coq.nvim.

**Comment by mkubasz** [comment]
Oki :P That is tabnine service

**Comment by ms-jpq** [comment]
ok yeah thats why i disabled it by default, tabnine is like super heavy.

I mostly added it as a first class source because it's got very interesting (both good and bad) communication protocol, and in order to support it, it necessitated good design decisions for `coq.nvim` 

---

tabnine (free version anyways, I never paid for it) can't actually keep up with the average person's typing speed and has no built-in cancellation, so `coq.nvim` basically just puts a lock on tabnine's read - write sequence, and if tabnine just happens to be busy, `coq.nvim` basically returns zero results for that single request, and doesn't flood tabnine with more messages.

---

i will close this because well, i have zero control over how tabnine works, except in the communication, which I cannot improve beyond what i already have because the protocol requires everything to be synchronous.

i think the original designer of tabnine really thought he could get away with such an oversight, maybe the first versions of tabnine was really fast? its not super surprising though, because i think one of the maintainers of `youcompleteme` complained that the LSP specification was "unnecessarily complicated" because it didn't enforce strict ordering.

**Comment by mkubasz** [comment]
@ms-jpq Thanks for the info :) I actually paid for it, but If it is as slow as I saw maybe a good reason to consider something diference.
