### ISSUE TITLE
r_language_server, problem with completion following .

### ISSUE THREAD

**Issue by joiharalds** [ms-jpq/coq_nvim#303]
I'm using COQ and LSP r_language_server for .r files and am having problems with completion following a dot `.`

The problem is twofold.

### P1
COQ does not suggest anything after typing one letter or more following a dot, i.e.
`as.<LSP suggestions starting with as. appear like as.numeric>`
`as.n<No LSP suggestions appear, only buffer, TS, etc.>`

### P2
If I type a function name which includes a dot like `is.numeric()` or `as.numeric()` I will get LSP suggestions until I have typed `as.`. If I then select an LSP completion suggestion like `as.numeric` I get `as.as.numeric()` instead of `as.numeric()`.
This behavior is not present if I use manual omnicompletion `<C-x><C-o>` with `set omnifunc=v:lua.vim.lsp.omnifunc`

System info and minimal init.vim: https://pastebin.com/h4QzVufG

Gif showing behavior:
![coq_lsp_Rlang_error1](https://user-images.githubusercontent.com/14778057/134372343-c25e943e-914e-4e84-bf60-5be61c6960b7.gif)

This plugin is **awesome** and it would be super nice to have integration with the [Nvim-R plugin](https://github.com/jalvesaq/Nvim-R) but I'll open a separate feature request for that.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/305

P2 should be fixed, sorry about that.

will see what P1 is about

**Comment by ms-jpq** [comment]
for P1, `coq.nvim`'s cache is not smart enough.

right not it uses the "current word" to perform cache lookups.

so you typed `as.P` and intend to look for `as.POSIXlt.character($0)`, the cache tries to do a match with `P` against `as.POSIXlt.character($0)`, which fails because they are not similar enough.

this issue is that most LSPs simply send `POSIXlt` as the text to be filtered, but `rlanguageserver` sends the entire `as.POSIXlt.character($0)`

i will need to make the caching logic less naive.

as for the R plugin, i am not too sure what you want me to do with it?

just the `omnifunc` or what

**Comment by ms-jpq** [comment]
P1 has been fixed with more a more thorough heuristics, but there are still some issue with `rlanguageserver`.

mainly if you do:

![图片](https://user-images.githubusercontent.com/50598611/134424149-f9c5cda7-d63a-45f4-99a7-c067aa711a9e.png)

and select say `anyNA.data.frame()`,

it results in `data.anyNA.data.frame()` instead, which I assume is what you dont want? @joiharalds 

you want `anyNA.data.frame()` instead right?


---

however, this is more due to the fact that while the LSP allows `rlanguageserver` to specify a replacement region, it currently does not, if it did, the `data.` part would be simply replaced.

so ill close it as more of an upstream issue.

**Comment by joiharalds** [comment]
> P1 has been fixed with more a more thorough heuristics, but there are still some issue with `rlanguageserver`.

Thank you so much for your awesome work!

> and select say `anyNA.data.frame()`,
> 
> it results in `data.anyNA.data.frame()` instead, which I assume is what you dont want? @joiharalds
> 
> you want `anyNA.data.frame()` instead right?

Yes, that's correct.

> however, this is more due to the fact that while the LSP allows `rlanguageserver` to specify a replacement region, it currently does not, if it did, the `data.` part would be simply replaced.
> 
> so ill close it as more of an upstream issue.

I'll ping the `rlanguageserver` maintainers to take a look at this issue.

For the `Nvim-R` plugin, yes, I'm thinking of the omnifunc sources. But then it's probably just a matter of porting them so they can be used with `coq`. If that's the case I could just take a look at it myself. Plus, I'm not even sure that this is worth doing because maybe the R_lsp is a sufficient source on its own. So I don't want to open a feature request on this until I have looked into this myself :)
