### ISSUE TITLE
Clangd snippets

### ISSUE THREAD

**Issue by Midren** [ms-jpq/coq_nvim#314]
When I am inserting completion in C++ with clangd, it seems like inserts some snippets, which coq_nvim is not handling properly.

Examples:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/32875119/134814547-de9dbef1-9457-44c0-9865-43b1fbaed53c.png">

<img width="374" alt="image" src="https://user-images.githubusercontent.com/32875119/134814668-57554769-563d-4b21-a255-2bec59665018.png">

I tried to disable snippetSupport in LspConfig, but it didn't help.

**Comment by ms-jpq** [comment]
sorry can you please do ":messages" and post back when you select the snippets? 

if the snippets didnt parse, coq will print out a small error, thanks!

**Comment by Midren** [comment]
It just:
⛔️ No more marks available

**Comment by ms-jpq** [comment]
ok cool ill install it later and see whats up, it's probably the snippet flag sent from LSP are either not read, or LSP never sent them

so coq just assumes they are text

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/316

ok i fixed it, the issue was LSP allows sending of edits that specified ranges to update, and I once I put those in cache, I basically said "ok the old ranges no longer work, I will insert a fallback and treat them like non-snippets"

except the fallback was... also snippets because I didn't think to check if the fallback was exactly the same as the primary insertions.

---

unrelated: clangd is the best LSP ive seen in terms of completion results, holy crap.

annnnnnd I had to fix one more bug related to it, so now you will see snippets everywhere in clangd.

<3
