### ISSUE TITLE
How to select a suggestion without inserting newline character?

### ISSUE THREAD

**Issue by raziman18** [ms-jpq/coq_nvim#34]
I know that `<cr>` is the keybinding to select a suggestion but it inserts newline as well. Is there any way to prevent this from happening?

![coq_nvim](https://user-images.githubusercontent.com/50593529/129565484-5e12e291-a4d4-419c-854f-9e2db8bd015e.gif)

**Comment by raziman18** [comment]
I think this commit 0a5a2bf208e07b69519220a993057f68cf362204 has fixed this bug

**Comment by janbuchar** [comment]
I don't think the referenced commit changed anything - I can still see the issue on dev (bccaf007ea9f861557387b4ec3a514d23ce04e82) and coq (69976db541a294837741f6905c8a4197678d3ecf) branches. Not only does it insert a newline, it also messes up the undo history.

**Comment by ms-jpq** [comment]
This is really weird.

The remapping [line in question](https://github.com/ms-jpq/coq_nvim/blob/9ef9e8158b6c8817ed5a385d67d0ca84efb52438/coq/server/registrants/options.py#L60) should not break `<cr>` for people in theory.

`<cr>` gets remapped to `pumvisible() ? (complete_info(['selected']).selected == -1 ? '<c-e><cr>' : '<c-y>') : '<cr>'`

so when you do a select, it should hit `<c-y>`, and `<cr>` isn't even entered.

---

and if this was indeed the behaviour for most people, this will be the `#1` issue, since it's a terrible default.

most people are not complaining though, but now there are two issues with the same behaviour, so my best guess is that there is some conflict in either `autocmd` or `mapping`, and the conflict is not super rare, probably due to another extension.

---

I do not have a hypothesis on what the conflict is, but it would be really helpful if i can have your `vimrc` @issadarkthing

**Comment by raziman18** [comment]
My config is in a hot mess right now but here is my config https://github.com/issadarkthing/nvim-config.git

**Comment by zeertzjq** [comment]
Maybe you auto pair plugin is interfering with it. Try running `:imap <CR>` and see what it is mapped to.

**Comment by zeertzjq** [comment]
I can see you are using `jiangmiao/auto-pairs`. Try searching that repository for "pumvisible" and see if there are any issues that can solve your problem.

**Comment by raziman18** [comment]
I'm not able to copy paste the result, so here's the screenshot of it's output
![image](https://user-images.githubusercontent.com/50593529/131287193-d660dad1-48e0-46a3-b353-411acd725008.png)

**Comment by raziman18** [comment]
indeed `jiangmiao/auto-pairs` is the culprit of this bug. I've confirmed it by disabling it.

**Comment by zeertzjq** [comment]
Try mapping `<CR>` to this: `pumvisible() ? (complete_info().selected == -1 ? "<C-e><Plug>AutoPairsReturn" : "<C-y>") : "<Plug>AutoPairsReturn"` using options `{ expr = true, noremap = false }`.

**Comment by ms-jpq** [comment]
yeah ok, thanks @zeertzjq  and @issadarkthing .

I will close this for now since it's a user mapping isue

**Comment by raziman18** [comment]
@zeertzjq though the mapping works but it no longer indents after `<cr>` in a closed pair.
Taking from their doc
```
Insert new indented line after Return: >

        input: {|} (press <CR> at |)
        output: {
            |
        }
```
