### ISSUE TITLE
Add release version tagging

### ISSUE THREAD

**Issue by ljmf00** [ms-jpq/coq_nvim#354]
Users should be able to use recognized tags for version pinning or for plugin managers to update patch versions automatically, but keep breaking changes away from users workflow.

Please consider using [semver.org](https://semver.org/) standard or something similar to tag this plugin.

**Comment by ms-jpq** [comment]
humm since nvim isn't 1.0 yet, I can't say its a good idea to tag versions.


Because upstream APIs are not stable yet, and there was a breaking change recently. (maybe 1 more? I havn't read the github thread yet)


so even if you do version pinning you might end up with tags of `coq.nvim` that is out of sync with the latest vim version, and if people just assume those are the stable `coq.nvim` versions (I certainly would, not everybody reads the README.md), they will end up with a broken install.



`coq.nvim` do try to keep stable user facing interfaces, and has zero public APIs that third party authors can tap into, so I am not even sure if tagging is worth it overall.


anyways I will close this for now.
