### ISSUE TITLE
Function gets printed directly in buffer

### ISSUE THREAD

**Issue by LamprosPitsillos** [ms-jpq/coq_nvim#407]
https://user-images.githubusercontent.com/61395246/145686114-4a0d1b27-9e10-4503-8687-fb284041bcab.mp4

Is there a way to stop this from happening?
What i expect to happen is for the function to be autocomplete for me , not the whole Function definition .

**Comment by ms-jpq** [comment]
sorry which LSP is this, I will fix it but it would be really helpful if I can know

**Comment by LamprosPitsillos** [comment]
For me it was ccls

**Comment by ms-jpq** [comment]
ok yeah i found out why, its caused by the cache, which when it encounters an item that specifies a range of text to update, it tries to remove the range parameter because you know, the range of text might be not vaild anymore.

this works pretty well, until you hit snippets. in which case, I have to think pretty hard what to do. Most LSPs do provide some sort of fallback for this, but `ccls` doesn't.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/425

**Comment by Supreeeme** [comment]
I'm still seeing this behavior, but only with struct members and variables. Using ccls.

**Comment by rbrugo** [comment]
I'm still seeing this behavior, with the following configuration:
```lua
local lsp = require 'lspconfig'
local coq = require 'coq'

lsp.ccls.setup(
    coq.lsp_ensure_capabilities({
        init_options = {
            compilationDatabaseDirectory = "build";
            client = {
                snippetSupport = false;
            };
            completion = {
                placeholder = false;
            }
        }
    })
)
```
If the completed function is not in the namespace `std`, the whole function signature is printed in the buffer.
Do you know any workaround for this?
