### ISSUE TITLE
Possible to use without auto completion?

### ISSUE THREAD

**Issue by jandamm** [ms-jpq/coq_nvim#44]
Is it possible to use coq without the popup window and just open a popup when pressing `<c-space>`?
If yes, would it still cache results in the background?

It's really fast but I'd prefer no autocompletion 👍

**Comment by ms-jpq** [comment]
not currently, but i can add that :)

will let you know when i am done.

---

but no it wont cache meaningful results in background.

Because the cache engine will (and should imo) invalidate cache, if you move ur cursor to entirely different places in the document between hitting `<c-space>`, which is what I would expect to be the use case.

How the cache engine works exactly is an implementation detail, but roughly, it computes a range of cursor positions that you are likely to type  1-2 symbols in, and if you veer away from that, the engine will ask for brand new results.

Its more optimized for normal typing where we are typing word by word, maybe with some backspace and such.

**Comment by jandamm** [comment]
Thanks for the fast reply :)

I'd use it somewhat like this:

```swift
guard let tableView = tableView else { return }
tableView.someLongFunctionIDontKnowTheNameOf(...)
```

I'd type:
```
guard let ta<C-p> = <C-p> else { return }
ta<C-p>.some<C-SPACE>
```

For keywords like guard, let, else and return I don't need completion.
For local variables most of the time it's faster to just complete bufwords (<C-p>).
But then for methods and functions completions are really valuable.

In theory the engine could compute the results in the background. 
But then again it's a lot of computations for nothing so I'm not sure if it would be worth it.

**Comment by hwo411** [comment]
Would be great to have such feature!

@jandamm as a workaround, you can go to plugin folder, open file 

`coq/server/registrants/attachment.py`

And comment the line
`atomic.exec_lua(f"{NAMESPACE}.{_listener.name}()", ())`

which is currently line 98:
https://github.com/ms-jpq/coq_nvim/blob/b822ca0b8deb9238200802d0816f0b451117557b/coq/server/registrants/attachment.py#L98

Comment char for python is `#`, so the line comes `# atomic.exec_lua(f"{NAMESPACE}.{_listener.name}()", ())`

Not sure if it breaks anything else, since I only started using this plugin, but hope that helps.

**Update:** actually it breaks BUF suggestions, but since I use LSP, it doesn't affect me. There might be some better workaround.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/blob/coq/docs/COMPLETION.md

**Comment by ms-jpq** [comment]
there is a toggle now

**Comment by jandamm** [comment]
Thanks 👍
