### ISSUE TITLE
How to use with asdf?

### ISSUE THREAD

**Issue by Secretmapper** [ms-jpq/coq_nvim#60]
asdf is a tool for [managing runtimes](https://asdf-vm.com/). Unfortunately, it doesn't seem to have python-venv.

Has anyone been able to use coq_nvim with asdf?

Might be related:
https://github.com/asdf-vm/asdf/issues/636
https://github.com/danhper/asdf-python/issues/64

**Comment by ms-jpq** [comment]
I use asdf right now, the python it compiles should have `venv` module installed by default?

**Comment by ms-jpq** [comment]
ok i will close this, since is not super related, and OP didnt reply.

but the jist is that `asdf` will sometimes compile the languages to be installed, and `venv` might be not installed as a part of the compilation, but I am pretty sure if you install all the suggested dependencies, `asdf` will have `venv` by default.

If not, that is more of an `asdf` support ticket. (or not even, I think the `asdf` team just out sources the python compilation from another big project)
