### ISSUE TITLE
Put cursor between brackets after completion

### ISSUE THREAD

**Issue by tydra-wang** [ms-jpq/coq_nvim#85]
`_` stand for cursor.
```
# what i want
myfunc(_)
# what i got
myfunc()_
```

**Comment by ms-jpq** [comment]
This depends on your LSP, if your LSP spits out something like `myfunc($0)`, the cursor will be placed where `$0` is. (This is actually how LSPs do it, they use snippet syntax, and clients parse those snippets with cursor placement info)

You can view the [specification here](https://github.com/microsoft/language-server-protocol/blob/main/snippetSyntax.md), the `$0` is a special symbol for cursor location.

But if your LSP spits out `myfunc()`, then `coq.nvim` will not try to place the cursor between the brackets. Since there is noway for `coq.nvim` to know that if `myfunc` actually takes arguments or not.

Now `coq.nvim` does try to perform a bit of guessing when placing the edits, due to its error correction logic, and a bit more heuristics based on the grammar of major language families, but I feel like those are actually more solid, and less coin flippy.

**Comment by tydra-wang** [comment]
@ms-jpq 

Thank you for your explanation.

I tried gopls and pyright, while neither of them work as I wish. They do work when using coc.nvim or vscode. Am I missing something in my config? I would be grateful if you can help me fix this!

```lua
local nvim_lsp = require('lspconfig')

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

nvim_lsp.pyright.setup(require('coq')().lsp_ensure_capabilities({
  capabilities = capabilities,
}))

nvim_lsp.gopls.setup(require('coq')().lsp_ensure_capabilities({
  cmd = {'gopls', '--remote=auto'},
  capabilities = capabilities,
  settings = {
    gopls = {
      experimentalPostfixCompletions = true,
      analyses = {
        unusedparams = true,
        -- shadow = true,
     },
     staticcheck = true,
    },
  },
}))
```

In .py, I typed `pandas.` and selected `read_csv`. I got:
```python
import pandas
pandas.read_csv|
```

In .go, I typed `strings.` and selected `HasPrefix`. I got:
```go
strings.HasPrefix()|
```

`|` stands for the cursor.

**Comment by mortezadadgar** [comment]
@ms-jpq why it's closed, the cursor is always after the paranteses with go this's not the expected behaviour

**Comment by ms-jpq** [comment]
because I didn't want to make `coq.nvim` try to alter LSP response and inject additional behaviour.

I will take a look at if `coq.nvim` is spec compliant again since you asked for it, but I will not deviate from the specs too much.

it is certainly possible that I missed some other way of specifying cursor positions from the LSP specs.

---

I absolutely do not have the bandwidth to maintain a list of LSPs and try to individually optimize their output, for example, if `gopls`  do not implement smart `$0` positioning, I will not add that myself.

between the three main family of languages, `ml`, `lisp` and `c`, there is zero consistent way of putting `()`.

**Comment by mortezadadgar** [comment]
I don't think nvim-cmp manages this per LSP @hrsh7th does it?

**Comment by ms-jpq** [comment]
I found & fix a non-compliant bug, should be ok now?

please re-open if you see anything funny!
