### ISSUE TITLE
Change suggestion order

### ISSUE THREAD

**Issue by SamuelTJackson** [ms-jpq/coq_nvim#92]
Hey,
when I write `fmt` in golang I get the correct suggestions:
![image](https://user-images.githubusercontent.com/14303082/130110470-5ed41073-961f-4505-86ad-adea1503af05.png)
Then I type P and at the first place is a suggestion from a buffer which would not even work. 
![image](https://user-images.githubusercontent.com/14303082/130110636-32177720-7459-4370-ab34-8f8e8a1212fe.png)
Is it possible to see only valid suggestions or at least change the order? 

I never used `fmt.ProvideCountryCache` why is it suggested to me at all?

**Comment by ms-jpq** [comment]
the emphasis is on **valid suggestions**, which I assume you meant LSP suggestions, and you want to rank it above everything else.

which I could add as an option, but definitely not as a default, some LSPs are very good and will do proper server side filtering, other LSPs will not, and therefore their suggestions are basically barely above `buffers` or `treesitter` in quality.

---

why are non `LSP` suggestions even suggested to you?  well its simple, because they are way faster, and work without needing LSP servers. 

If you want, you can disable every non-LSP source out there.

**Comment by ms-jpq** [comment]
For the most part I do not want to give users too much control over the [1st parameter of the lexicographically sorted ranking algorithim](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/FUZZY.md), it has some knobs you can tune, but due to the weighted average of relative ranks approach, the parameter is too sensitive for delicate knob turning.

If you add an extra weight to it, it will most likely be destructive to the overall goals of a good ranking.

---

that is not to say I will not add this in the future.

maybe I can pre-process all the users parameters through something like a sigmoid function (commonly used in ML), but that needs to be something carefully considered first.

**Comment by ms-jpq** [comment]
basically the goal of a sigmoid function hand hold the users, so they do not need any particular knowledge about the algorithms in order to tune them. or else adding in tuning parameters is like giving `coq` users a foot gun.

**Comment by SamuelTJackson** [comment]
My point is the following and excuse me if I'm talking shit because I have no idea:D 
When I type `fmt.` coq is already suggesting all the available functions for me from the lsp source. At this point coq already got all possible and best solutions and don't need to give me some suggestion from an other source, because it can't be better then from the lsp source. So just an other example. Writing `fmt.` gives me:
![image](https://user-images.githubusercontent.com/14303082/130128814-f79f36ce-a024-4263-85db-63a89e08f5ec.png)
And then sometimes after writing an other character it looks like this:
![image](https://user-images.githubusercontent.com/14303082/130128894-4be71454-b205-4fa7-9db4-212fdf40eb2e.png)
On the second image is not one valid suggestion. It feels wrong that the suggestions without any input are better then with an additional character. 

Maybe it's possible that you add an option that, when enabled, allows you to chose only from lsp source after retrieving the lsp suggestions once. Or something like this.

By the way I really appreciate your program and love how much work you put into it! <3

**Comment by ms-jpq** [comment]
oh i see what you mean, it also has to do with timeouts as well, in the second picture I presume your LSP server did not respond within `0.088` seconds and its results were discarded, or went straight into the cache, depending on how the `LSP` server responded (like HTTP servers, they send `cache` "headers")

I think if you find `0.088` seconds too short, you can increase it. because alot of LSP servers cannot respond that fast, but that also has the side effect of slowing down on every keystroke, as everything else waits for the LSP servers.

---

the reason why `.` will have more response is actually because it looks like **no other sources found anything**, then in that case `coq.nvim` will intelligently wait until one of the sources has found something, because then an early return will be pointless and yield zero results anyways.

for `.P`, other sources can actually match stuff, so they have responded, and LSP is too slow in that case.

This is not very straight forward, what you are seeing here is the trade offs of the optimizations I have put into place.

**Comment by ms-jpq** [comment]
also i chose lots of 8s and 6s because they are lucky numbers, not cuz jojo rabbit

**Comment by ms-jpq** [comment]
im gonna reopen it because i want to do the sigmoid function thing, its gonna be fun :)

**Comment by elkowar** [comment]
I think having the option to have the sorting happen within a given source, but then declare a general, more prioritized order for different sources, would be really really nice.
What i mean by that is that it'd be great if we could say
`"[BUF]" is _always_ less important than "[LSP]" and should thus always be lower.`

as someone mostly using _really_ good LSPs such as rust-analyzer, the (mostly useless) BUF completions commonly being much higher than the much more useful makes coq barely usable at all (i use completion mostly to _find_ stuff, not to save on typing time - i can type plenty fast, but I can't look up docs as fast as typing in my editor)

I'd consider this a must-have feature in the current state, specifically because with my way of using completions to see what functions exist, having invalid BUF completions in there means that I can't trust the completions anymore. Completely disabling that source would be anoying, too, as then I'd not have it available in files without any LSP (such as plain text, markdown, etc)

**Comment by ms-jpq** [comment]
This will be worked on next PR, but I explicitly do not want to have a blanket **source always higher** option. That is too crude and LSPs vary in quality greatly. 

You can get into the situation where you use both `rust-analyzer` (high quality) and `typescript lsp` (bad quality), but then treating them the same. (I in fact use both quiet frequently)

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/110

---

##### `coq_settings.clients.<x>.weight_adjust`

Weight adjustment for ranking, normalized to `[0.5, 1.5]` using `S(x) = 1 / (1 + e^-x) + 0.5`

Ideally pick a number between `[-2, 2]`.

`S(0) = 1` no adjustment

`S(-2) ~= 0.6` anything smaller has diminishing returns

`S(+2) ~= 1.4` anything bigger has diminishing returns

---

Right now all the weight adjustments are set to 0, meaning no adjustment. 

I will just push out this for now, and figure out good guesstimate defaults this weekend.

**Comment by ms-jpq** [comment]
a default was set, i forgot to close this issue
